Django/django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^todo/', include('todo.urls')),
]

Django/django_app/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)+/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

Django/django_app/todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^remove/$', views.remove_item, name='remove'),
    url(r'^complete/$', views.mark_complete, name='complete'),
]

Django/django_app/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django/django_app/todo/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

# Create your models here.

class ToDoItem(models.Model):
    name = models.CharField(max_length=50)
    due_date = models.DateTimeField(default=datetime.today)
    is_completed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

Django/django_app/tvmaze/models.py
from django.db import models

# Create your models here.

Django/django_app/todo/forms.py
from django import forms
from todo.models import ToDoItem

class ToDoForm(forms.ModelForm):
    name = forms.CharField(max_length=50, label="Action Item")
    due_date = forms.DateTimeField(label="Due Date", required=False)

    class Meta:
        model = ToDoItem
        fields = ('name','due_date')

Django/django_app/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Count

from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
                               #.annotate(num_choices=Count('choice')) \
                               #.filter(num_choices__gte=1) \
                              # .order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    """
    Excludes any questions that aren't published yet.
    """
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Django/django_app/todo/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect

from . import forms, models
# Create your views here.

@csrf_protect
def index(request):
    todo_list = models.ToDoItem.objects.all()

    if request.method == 'POST':
        form = forms.ToDoForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            # reset the form and return to index page
            form = forms.ToDoForm()
            return render(request, 'todo/index.html', {'form': form, 'todo': todo_list})
        else:
            print form.errors
    else:
        form = forms.ToDoForm()

    return render(request, 'todo/index.html', {'form': form, 'todo': todo_list})

def remove_item(request):
    if request.method == 'POST':
        del_item = request.POST.get("remove_button", "nothing found")

        if not del_item == "nothing found":
            m = models.ToDoItem.objects.get(id=del_item)
            print m
            m.delete()

    if 'next' in request.GET:
        return redirect(request.GET['next'])
    return render(request, 'todo/base.html')


def mark_complete(request):
    if request.method == 'POST':
        completed_item = request.POST.get("model_id", "nothing found")
        
        if not completed_item == "nothing found":
            m = models.ToDoItem.objects.get(id=completed_item)
            m.is_completed = True
            m.save()


    if 'next' in request.GET:
        return redirect(request.GET['next'])

    return render(request, 'todo/base.html')

Django/django_app/tvmaze/views.py
from django.shortcuts import render

# Create your views here.

Django/django_app/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>
  {{ error_message }}
</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
  {% endfor %}
<input type="submit" value="Vote" />
</form>

Django/django_app/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}

Django/django_app/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }}
      vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

Django/django_app/todo/templates/todo/base.html
{% load staticfiles %}
<html>
    <head>
      {% block head %}
        <title>ToDo - {% block title %}{% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

      {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}

        {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'todo/todo.js' %}"></script>
        {% endblock %}
    </body>
</html>

Django/django_app/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block title%}Index{% endblock %}
{% block body %}
<div class="container">
  <div class="jumbotron">
    <h1>ToDo List App</h1>
    <hr>
    <form role="form" method="post" action={% url "todo:index" %} class="post-form">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        {{ field.help_text }}
        <p>{{ field.label }}: {{ field }} <span style="color:red">{{ field.errors }}</span></p>

      {% endfor %}
      <button type="submit" class="glyphicon glyphicon-plus">Submit</button>
    </form>
    <hr>
    <br/>
    <table class="table table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Action Item</th>
          <th>Due Date</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
      {% for item in todo %}
        <tr>
          <td>
            <form role="form" method="post" action="{% url "todo:complete" %}?next={% url "todo:index" %}" class="form-inline">
              {% csrf_token %}
              <a class="chkbx" id="{{ item.id }}" href="#{{ item.id }}">
              <span class="glyphicon glyphicon-unchecked"></span></a>
              <input name="model_id" type="hidden" value="{{ item.id }}">
            </form>
          </td>
          <td>
            {% if item.is_completed %}
              <span class="todo-text" style="text-decoration:line-through;">{{ item.name }}</span>
            {% else %}
              <span class="todo-text">{{ item.name }}</span>
            {% endif %}
          </td>
          <td><span class="badge"> {{ item.due_date }}</span></td>
          <td>
            <form role="form" method="post" action="{% url "todo:remove" %}?next={% url "todo:index" %}" class="form-inline">
              {% csrf_token %}
              <button name="remove_button" value="{{ item.id }}" type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-remove">
              </button>
            </form>
          </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
  </div>
</div>

{% endblock %}